services:
  app:
    image: ghcr.io/christianfosli/bike-count/app
    build:
      context: .
    ports:
      - 8501:8501
    develop:
      watch:
        - action: sync
          path: bike_count.py
          target: /app/bike_count.py
        - action: rebuild
          path: requirements.txt
