name: 'cicd'
on:
  push:
    paths-ignore:
      - README.md
      - infra/**

permissions:
  # required to push to ghcr
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add build tags to docker-commpose.yaml
        run: |
          dockerRepo="$(yq '.services.app.image' docker-compose.yaml)"

          TAG="$dockerRepo:$(git rev-parse --short HEAD)" yq -i '.services.app.build.tags[0] = strenv(TAG)' docker-compose.yaml

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            printf 'Banch is main! Adding latest as build tag\n'
            TAG="$dockerRepo:latest" yq -i '.services.app.build.tags[1] = strenv(TAG)' docker-compose.yaml
          fi

          cat docker-compose.yaml | yq '.services.app.build'

      - name: Build with docker
        run: docker compose build app

      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to ghcr
        run: docker compose push app
