name: 'infra'
on:
  push:
    branches:
      - main
    paths:
      - 'infra/**'
  workflow_dispatch:

permissions:
  # required for federated credentials access to azure
  id-token: write
  # required for federated credentials access to azure
  contents: read

jobs:
  deploy:
    strategy:
      max-parallel: 1
      matrix:
        environment: [dev, prod]
    runs-on: ubuntu-latest
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v1
        with:
          client-id: ${{ vars.AZ_CLIENT_ID }}
          subscription-id: ${{ vars.AZ_SUBSCRIPTION_ID }}
          tenant-id: ${{ vars.AZ_TENANT_ID }}

      - name: Preview changes
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-bikecount-${{ matrix.environment }}
          template: ./infra/main.bicep
          parameters: environment=${{ matrix.environment }} hostName=${{ vars.CA_HOST_NAME }}
          additionalArguments: "--what-if"

      - uses: azure/arm-deploy@v1
        with:
          resourceGroupName: rg-bikecount-${{ matrix.environment }}
          template: ./infra/main.bicep
          parameters: environment=${{ matrix.environment }} hostName=${{ vars.CA_HOST_NAME }}
